### ISSUE TITLE
typescript: No semicolon on last field of inline interface

### ISSUE THREAD

**Issue by nayeemrmn** [dsherret/dprint#102]
input:
```ts
let a: { b: number; c: number };
```

prettier: (preserves)

dprint:
```ts
let a: { b: number; c: number; };
```

(For multiline
```ts
let a: {
  b: number;
  c: number;
};
```
the behaviour already matches.)

**Comment by dsherret** [comment]
I don't like that code 😉

I'm going to add some configuration here. Perhaps the `semiColon` rule should not be `true` / `false`, but something else like `always` / `somethingAboutNotTrailingWhenSingleLine` / `somethingAboutInsertionAtTheStartOfSomeExpressionStatements` then that propagates down the the specific AST node config that can be a boolean or this enum depending on the kind of node.

Need to think about it, but let me know if you have any suggestions or ideas.
