### ISSUE TITLE
Use single quote if string contains a double quote (more doubles than singles)

### ISSUE THREAD

**Issue by hayd** [dsherret/dprint#103]
```diff
-const statusOK = '{"status":"OK"}\n';      // prettier
+const statusOK = "{\"status\":\"OK\"}\n";  // dprint
```

In [prettier](https://github.com/prettier/prettier/tree/21733e441dc01f7d85b483edee92b7e7507bfd9a#quotes): 

> If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: "I'm double quoted" results in "I'm double quoted" and "This \"example\" is single quoted" results in 'This "example" is single quoted'.

**Comment by dsherret** [comment]
Probably going to change `singleQuotes: boolean` config to `quoteStyle: "alwaysDouble" | "alwaysSingle" | "preferDouble" | "preferSingle"` with `"preferDouble"` as the default.

**Comment by dsherret** [comment]
Yup, went with that. Thanks for bringing this up @hayd!
