### ISSUE TITLE
Differences in Prettier and dprint formatting for correction

### ISSUE THREAD

**Issue by David-Else** [dsherret/dprint#105]
I am assuming the goal in Deno with dprint is to replace Prettier and keep the same formatting, so I made a note of the differences as of today in my current project in the hope they can be ironed out:

prettier
```
  return currentWidthToHeight > targetWidthToHeight
    ? // window width is too wide relative to desired game width
      [currentHeight * targetWidthToHeight, currentHeight]
    : // window height is too high relative to desired game height
      [currentWidth, currentWidth / targetWidthToHeight];
}
```
dprint
```
  return currentWidthToHeight > targetWidthToHeight
    ? // window width is too wide relative to desired game width
    [currentHeight * targetWidthToHeight, currentHeight]
    : // window height is too high relative to desired game height
    [currentWidth, currentWidth / targetWidthToHeight];
}
```
prettier
```
    linesOfText.forEach((line, index) =>
      ctx.fillText(line, 0, index * this.fontSize)
    );
```
dprint
```
    linesOfText.forEach(
      (line, index) => ctx.fillText(line, 0, index * this.fontSize)
    );
```
prettier
```
    const gravesPos: Vector2 | null | undefined =
      globalState.gameData.level1.graves[0].position;
```
dprint
```
    const gravesPos: Vector2 | null | undefined = globalState.gameData.level1
      .graves[0].position;
```
prettier
```
    context.entities.screenText[0].text = `Level 1\nLives = ${context.entities.hero.lives}\nScore = ${context.score}\nZombies = ${context.entities.zombies.length}\nBullets = ${context.entities.hero.numberOfBullets}`;
```
dprint
```
    context.entities.screenText[0].text = `Level 1\nLives = ${context.entities
      .hero.lives}\nScore = ${context.score}\nZombies = ${context.entities
      .zombies.length}\nBullets = ${context.entities.hero.numberOfBullets}`;
```
prettier
```
  entitiesGroupOne.forEach((entity, indexOne) =>
    entitiesGroupTwo.forEach((entityTwo, indexTwo) => {
```
dprint
```
  entitiesGroupOne.forEach(
    (entity, indexOne) => entitiesGroupTwo.forEach((entityTwo, indexTwo) => {
```
keep up the great work, thanks!

**Comment by dsherret** [comment]
@David-Else thanks for showing these scenarios! I haven't been striving for this to be the same as Prettier, but there is precedent in what Prettier has done so I will make changes on a case by case basis.

This is all changed except for the first example. I've opened #114 for that as I'll need to think about it some more.

By the way, Prettier does some strange things with template literals that don't seem to make sense (Ex. make the first expr in one of those template literals a call expression and the whole thing formats strangely). I'll make fixes in that area on a case by case basis going forward.

**Comment by David-Else** [comment]
@dsherret Nice one! 

You are right, Prettier does some strange things with template literals, that is the only thing I have had problems with, so improvements there would be great :)
