### ISSUE TITLE
[bug]: Incorrectly removed semicolon at the end of the for loop

### ISSUE THREAD

**Issue by zhmushan** [dsherret/dprint#108]
```ts
for(;;);
```
related: https://github.com/denoland/deno/issues/4025

**Comment by dsherret** [comment]
This is a for statement with a body that’s an empty statement. I recently changed the behaviour to not print anything for empty statements, but as you’ve shown that shouldn’t always be the case.

Thanks for opening!

**Comment by dsherret** [comment]
Fixed and released in 0.6.1 (will be fixed in the next version of deno).

**Comment by zhmushan** [comment]
Thanks！
