### ISSUE TITLE
Debug panic when formatting assignment pattern with type annotation

### ISSUE THREAD

**Issue by ry** [dsherret/dprint#117]
using this config
```rust
  dprint::configuration::ConfigurationBuilder::new()
    .line_width(80)
    .indent_width(2)
    .next_control_flow_position(
      dprint::configuration::NextControlFlowPosition::SameLine,
    )
    .binary_expression_operator_position(
      dprint::configuration::OperatorPosition::SameLine,
    )
    .build()
```

On this file: https://github.com/denoland/deno/blob/e53064c4f22efeb8a4eda2712e15c77d2699a686/cli/js/console.ts

stack trace https://gist.github.com/ry/b5ca2d16e18a3eb31b6268a7fc25ac00

**Comment by dsherret** [comment]
@ry are you starting to format Deno's TypeScript code using dprint? You might want to at least wait until I implement #94 (I've been making [steady progress](https://github.com/dsherret/dprint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+preferHanging) on the `preferHanging: false` in other areas and that's the last one).

After that, it's basically #64 and #61, but you should be able to start formatting without those.

Btw, I'm busy tonight and the next few nights so I'll get back to this on the weekend.

**Comment by ry** [comment]
> are you starting to format Deno's TypeScript code using dprint

Nope, just keeping an eye on where your progress is.

**Comment by dsherret** [comment]
Oh, nice. This is a `#[cfg(debug_assertions)]` only panic that indicates the possibility for comments to be formatted in the wrong place (I should add that info to the panic message).

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/pull/693
