### ISSUE TITLE
Add top level "prettier" config

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#147]
This would change the config to be as close to prettier as possible.

I'm slightly concerned by adding this that people would expect it to act exactly like prettier in all edge cases, but I assume people will be reasonable...

**Comment by ry** [comment]
I think a docstring comment that specifies it's not intended to be exact, only close, would solve that.

From my understanding it would just be an alias for
```
    .line_width(80)
    .indent_width(2)
    .next_control_flow_position(NextControlFlowPosition::SameLine)
    .binary_expression_operator_position(OperatorPosition::SameLine)
    .brace_position(BracePosition::SameLine)
    .comment_line_force_space_after_slashes(false)
    .construct_signature_space_after_new_keyword(true)
```
