### ISSUE TITLE
Add configuration for forcing comment text to fit in line width

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#15]
Right now comments are left as-is other than the space added on single line comments, but it might be good to add a configuration option that will split them up when they exceed the line width. I'm not sure if this should apply to trailing comments, but it should apply to ones on their own line.

Idea provided to me by @macterra while I was talking to him about this.

Also, would be cool to maybe have some kind of balancing in order to make the right side look somewhat justified.

**Comment by dsherret** [comment]
Not going to bother with this for the time being.

**Comment by Soremwar** [comment]
Is it a good time now to reconsider?
