### ISSUE TITLE
Update formatting to be in line with Prettier 2.0 “2020”

### ISSUE THREAD

**Issue by David-Else** [dsherret/dprint#155]
https://prettier.io/blog/2020/03/21/2.0.0.html

**Comment by dsherret** [comment]
Thanks, I was looking at this last night. It's good that they have fixed a lot of these issues (I was noticing some of them when looking at what prettier does in certain scenarios).

I'll update some of the defaults and change the `.prettier()` config to match 2.0.

**Comment by dsherret** [comment]
Still a lot to fix based on that doc, but I have made the general config changes to align with prettier.
