### ISSUE TITLE
v0.9.4 Debug panic! Expected to have op token: :

### ISSUE THREAD

**Issue by ry** [dsherret/dprint#160]
on this file https://github.com/denoland/deno/blob/5d7bcf86fdb2bfcee0bfac24aeb7aeecb8b3faca/cli/tests/workers_test.ts

**Comment by dsherret** [comment]
@ry thanks, but could you hold off on opening more issues for a bit? I have a feeling that the latest swc minor version bump broke all this as there was a change related to token capturing, but maybe not.

I'm not seeing any of these files panic in the playground, but perhaps they are debug only panics.

**Comment by ry** [comment]
Sure - sorry for the flood  : )

Yes these are debug panics.

**Comment by dsherret** [comment]
@ry no problem! Yeah, my dprint tests panic when I delete my lock file and go from swc 0.21.6 to 0.21.7. I'll look into this tonight after work, but it's related to the fix for https://github.com/swc-project/swc/issues/726

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/728

**Comment by dsherret** [comment]
@ry I did a 0.9.5 release that pegs the swc_ecma_parser version. I think I'll keep it pegged from now on so I'm able to run every new swc version through my test suite before doing a release and so we don't run into this problem again.
