### ISSUE TITLE
Re-export swc for Deno

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#164]
It might be useful to re-export swc for use in Deno. This would help keep the swc dependencies in sync between Deno and Dprint.

**Comment by dsherret** [comment]
Hopefully I have done this correctly.

**Comment by bartlomieju** [comment]
@dsherret has this change been released to crates.io?

**Comment by dsherret** [comment]
@bartlomieju this is now available in dprint-plugin-typescript 0.9.9 🙂

Hopefully I did it right... it's my first time re-exporting anything in Rust.

**Comment by bartlomieju** [comment]
Thanks @dsherret I'll try it in the morning 🎉

**Comment by bartlomieju** [comment]
@dsherret works like a charm 👍
