### ISSUE TITLE
Dynamic import trailing commas

### ISSUE THREAD

**Issue by kitsonk** [dsherret/dprint#166]
Found another odd one...

```js
const foo = await import(
  "./foo.js",
);
```

Is actually invalid syntax and needs to be disallowed, as trailing commas are not allow in dynamic import statements.  Ref: https://github.com/tc39/proposal-dynamic-import/issues/15.

**Comment by dsherret** [comment]
@kitsonk interesting! Thanks, I’ll fix this tomorrow (today) once I wake up.
