### ISSUE TITLE
Arrow function with single parameter switches between formatting styles on each format

### ISSUE THREAD

**Issue by Soremwar** [dsherret/dprint#170]
Attempting to format this code:
[file.zip](https://github.com/dsherret/dprint/files/4457895/file.zip)

Will result in dprint switching between two different formatting styles. This results in git or file watchers getting confused thinking something in the code has changed and triggering events, even though the file was already formatted to begin with.

Example:

1 format:
```typescript
export const updateArea = async ({ params, request, response }:
  RouterContext) => {
```
2 format (nothing in file changed):
```typescript
export const updateArea = async (
  { params, request, response }: RouterContext,
) => {
```
3 format:
```typescript
export const updateArea = async ({ params, request, response }:
  RouterContext) => {
```

...infinite times

**Comment by dsherret** [comment]
Thanks for reporting @Soremwar! I think this was one of the failing examples in #157. I'll look into it soon.

**Comment by dsherret** [comment]
By the way, for now just add a `// dprint-ignore` comment above that line. I'll try to have this fixed soon.
