### ISSUE TITLE
Allow variable declarations on multiple lines

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#25]
For example:

```ts
var left  = '<pre><code\\b[^>]*>',
    right = '</code></pre>',
    flags = 'g',
```

**Comment by lazarljubenovic** [comment]
I personally don't like this style in any form, but I've seen people who like to add the leading comma when listing several declarations, so you might want to take that into consideration as an option.

```ts
var left  = '<pre><code\\b[^>]*>'
  , right = '</code></pre>'
  , flags = 'g'
```

And just in case you didn't notice, your example has a trailing comma which will break the file. :eyes:

**Comment by dsherret** [comment]
@lazarljubenovic good idea! Opened #26.

I'm not a fan of multiple variable declarations per statement either :)
