### ISSUE TITLE
Error about symbol being thrown

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#36]
Ironically this is the same example as in #35:

https://dprint.dev/playground/#code/HYQwtgpgzgDiDGEAEAXaKB0UD2kUAsBLYAcyQG8BYAKCTqQDMBXYeFQ7YVdACgEoKNesKSEGSHigBOTCAKq0RStFHakChHExST0xEgBUiUADTdV+o5oDy2zCABGhFC4wqUSALzekBvaSsMAGVbFABBABlnFAAbCAAhaJckAH5zNUNjUMwwbCl85AAudMssuz4AbiElJABfarp66lqgA/config/N4IgNglgdgpg6hAJgFwBYgFwEYBMAGAGhGkRimQRXQwBYiBXAZxgBUBDAI0cwDM2xmRZgFsIAYQD2YCVG4ZkAJ3owh0AOZgYARXoTkMOXwEqQithEhQ1k4cLZyQsAG4wFIBswBCCtgGMDmCAA7qhkAHJ6AMrqmgAy0DDuIBw+-gAKEowQyBAygbAAHsjxsACSPAASbFbqSVlWmp4SiACeGVk5eRggdtDI5lBJhciS5ApSAGLSQe3ZuYPdwyWJRBIADq5syBIKs50LjjBFy0k8O-4AsvRgOcsAggpq9MJkyIb8giBnCpfXtwlpNg+F76BTvYxEMjPAAiMF8YCBW3mADoXsIOK5Ims-LVur1yAMkkDxkEJvQoL59gBRAprBQGLIyZFMGCA+nkULMBz4-rQEAAXyAA

**Comment by lazarljubenovic** [comment]
This is super-weird, it's like it depends on the names of the variables.

https://dprint.dev/playground/#code/GYVwdgxgLglg9mABFApgZygCgJSIN4CwAUIqYjMIplAE4gq6ElkuoYxgDmUAFjGnBBY2sLgBU+aADTEWc5OlHdJgqADoRiALw7EYxR04T+agMoB5IQEEAMjChQANigBC9h1EQB+Be3GTEAC5fJV5+QQBPWXlEbABuaNIAX2IUoiA/config/N4IgNglgdgpg6hAJgFwBYgFwEYBMAGAGhGkRimQRXQwBYiBXAZxgBUBDAI0cwDM2xmRZgFsIAYQD2YCVG4ZkAJ3owh0AOZgYARXoTkMOXwEqQithEhQ1k4cLZyQsAG4wFIBswBCCtgGMDmCAA7qhkAHJ6AMrqmgAy0DDuIBw+-gAKEowQyBAygbAAHsjxsACSPAASbFbqSVlWmp4SiACeGVk5eRggdtDI5lBJhciS5ApSAGLSQe3ZuYPdwyWJRBIADq5syBIKs50LjjBFy0k8O-4AsvRgOcsAggpq9MJkyIb8giBnCpfXtwlpNg+F76BTvYxEMjPAAiMF8YCBW3mADoXsIOK5Ims-LVur1yAMkkDxkEJvQoL59gBRAprBQGLIyZFMGCA+nkULMBz4-rQEAAXyAA

https://dprint.dev/playground/#code/GYVwdgxgLglg9mABFApgZygCgJSIN4CwAUIqYjMIplAE4gq6ElkuoYxgDmUAFjGnBBY2sLgBU+aADTEWc5OlHdJgqADo2iALw7EYxR04T+agMoB5IQEEAMjChQANigBC9h1EQB+Be3GTEAC5fJV5+QQBPWXlEbABuaNIAX2IUoiA/config/N4IgNglgdgpg6hAJgFwBYgFwEYBMAGAGhGkRimQRXQwBYiBXAZxgBUBDAI0cwDM2xmRZgFsIAYQD2YCVG4ZkAJ3owh0AOZgYARXoTkMOXwEqQithEhQ1k4cLZyQsAG4wFIBswBCCtgGMDmCAA7qhkAHJ6AMrqmgAy0DDuIBw+-gAKEowQyBAygbAAHsjxsACSPAASbFbqSVlWmp4SiACeGVk5eRggdtDI5lBJhciS5ApSAGLSQe3ZuYPdwyWJRBIADq5syBIKs50LjjBFy0k8O-4AsvRgOcsAggpq9MJkyIb8giBnCpfXtwlpNg+F76BTvYxEMjPAAiMF8YCBW3mADoXsIOK5Ims-LVur1yAMkkDxkEJvQoL59gBRAprBQGLIyZFMGCA+nkULMBz4-rQEAAXyAA

**Comment by dsherret** [comment]
@lazarljubenovic it depends on the length of certain nodes and it's because of the change I made in #35.

Basically, while it prints stuff out it creates "save points"... so the printer prints ahead to get information (ex. is the next line hanging?) then it reverts back to the save point with the information it learned. The problem here was with restoring the save point.

I almost fixed it last night, but needed to go to sleep haha. I also wasn't able to think properly about the problem so starting on this fresh will help.

I've opened #37 to help ensure this doesn't happen again.

**Comment by dsherret** [comment]
One of the hardest bugs of my life! Ended up rewriting the printer to make it easier to understand and make restoring to save points way simpler. I still don't know what was wrong, but the redesign will make things easier going forward. I still need to clean it up eventually.
