### ISSUE TITLE
Remove `useSpaceSeparators` and only have per ast node configuration

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#47]
It would be better to remove the global `useSpaceSeparators` because I don't want certain behaviour by default.

For example, I like a space after an if keyword:

```ts
if (true) {}
```

But I don't like it after the function name:

```ts
function test () {
}
```

I also don't like it after the new keyword in constructor types and constructor function signatures:

```ts
new (...etc...)
```

`useSpaceSeparators` implies that there should be a space in both those cases.

---

Instead of the above, leave it to just having per AST node configuration.

Relates to #25.

**Comment by lazarljubenovic** [comment]
The spaces preferences really divide people in endless categories! I like spaces before parenthesis in function/method declarations, but not in calls.

```
function foo () { }
foo()
```

So that's another case 🤔
