### ISSUE TITLE
Leave empty blocks on the same line

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#65]
For example:

```ts
function test() {}
```

**Comment by nayeemrmn** [comment]
@dsherret 
Input:
```js
try {} catch {}
```
dprint output:
```js
try {
} catch {
}
```
Prettier output:
```js
try {
} catch {}
```
I know this seems arbitrary 😅, designing a formatter must be hard. I think Prettier's logic is add a new line for blocks which have no reason to be empty (`if`, `else`, `try`) and allow empty blocks for everything else (`while`, `for`, `catch`, functions).

Using options:
```rust
dprint::ConfigurationBuilder::new()
  .line_width(80)
  .indent_width(2)
  .next_control_flow_position(dprint::NextControlFlowPosition::SameLine)
  .binary_expression_operator_position(dprint::OperatorPosition::SameLine)
  .build()
```

**Comment by dsherret** [comment]
@nayeemrmn Thanks again! Opened #77
