### ISSUE TITLE
Fix try statement with empty catch

### ISSUE THREAD

**Issue by dsherret** [dsherret/dprint#77]
For example:

```ts
try {
    test;
} catch {}

// expected
try {
    test;
} catch {}

// actual
try {
    test;
} catch {
}
```

Also:

```ts
try {} catch {}

// expected
try {
} catch {}

// actual
try {} catch {
}
```

Via @nayeemrmn at https://github.com/dsherret/dprint/issues/65#issuecomment-580959847

**Comment by nayeemrmn** [comment]
There was also
```js
while (true) {}

for (let i = 0; i < 9; i++) {}
```

Expected: same

Actual:
```js
while (true) {
}

for (let i = 0; i < 9; i++) {
}
```

That should cover everything.

**Comment by dsherret** [comment]
The fix for this is easy that just requires a bit of cleanup refactoring to ensure everything is consistent. I'm going to fix this on the weekend when I can work on it with a fresh mind... usually I would just fix it, but I've been learning a new c++ codebase at work fixing multi-threading issues in some real-time signal processing code (lots of fun)... so to say the least, I'm fried 😅
