### ISSUE TITLE
Add spaceAfterTaggedTemplate

### ISSUE THREAD

**Issue by motss** [dsherret/dprint#87]
## Description

It'd be nice if there is a way to customize how space is added in tagged template.

**Actual sample code**

```ts
function html() {}

a = html`<div>${run()}</div>`;
```

**Formatted sample code**

```ts
function html() {}

a = html `<div>${run()}</div>`; // Space is added in between `html` keyword and the template literal
```

**Comment by dsherret** [comment]
For sure!

Implemented as `"taggedTemplate.spaceBeforeLiteral"`. Will be in the next release... whenever that is.

**Comment by motss** [comment]
Awesome. Thanks for the quick addition! 👍
