### ISSUE TITLE
typescript: Option for not wrapping lines at template string substitution

### ISSUE THREAD

**Issue by nayeemrmn** [dsherret/dprint#97]
Column limit of 80:

input (second line crosses 80 columns at the `123`):
```js
console.log(
  `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${123}aaaaaa`
);
```

prettier: (preserves)

dprint:
```js
console.log(
  `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${
    123}aaaaaa`
);
```

In other words, it might be desirable for simple expression substitutions to not be used as a wrapping point, and behave like a regular string literal.

**Comment by nayeemrmn** [comment]
For complex expressions (arrays and objects),

input:
```js
console.log(
  `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${[1]}aaaaaa`
);
```

prettier:
```js
console.log(
  `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${[
    1
  ]}aaaaaa`
);
```

dprint:
```js
console.log(
  `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${
    [1]}aaaaaa`
);
```

Just wanted to point this out for completeness. I don't know if providing the options to completely match prettier is a priority.

**Comment by dsherret** [comment]
I'll make this change without configuration.
